# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-28 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=100, null=True, verbose_name='标题')),
                ('document_url', models.CharField(max_length=300, null=True, verbose_name='文档地址')),
                ('is_collected', models.CharField(default='0', max_length=10, verbose_name='是否收藏')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 12, 28, 11, 19, 24, 727248), verbose_name='创建时间')),
                ('mobile', models.CharField(max_length=32, null=True, unique=True, verbose_name='手机号')),
                ('document_size', models.FloatField(default=0, verbose_name='文档大小')),
            ],
            options={
                'verbose_name': '文档信息',
                'verbose_name_plural': '文档信息',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=32, null=True, verbose_name='密码')),
                ('avatar_url', models.CharField(max_length=300, null=True, verbose_name='用户头像')),
                ('nick_name', models.CharField(max_length=300, null=True, verbose_name='用户昵称')),
                ('join_date', models.DateTimeField(default=datetime.datetime(2017, 12, 28, 11, 19, 24, 725784), verbose_name='加入时间')),
                ('phone', models.CharField(max_length=32, null=True, unique=True, verbose_name='手机号')),
                ('level', models.CharField(max_length=32, null=True, verbose_name='等级')),
                ('state', models.IntegerField(default=0, verbose_name='0:开启；1：禁用')),
                ('total_capacity', models.FloatField(default=0, verbose_name='容量')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_url', models.CharField(max_length=300, null=True, verbose_name='签名地址')),
                ('is_default', models.CharField(default='0', max_length=10, verbose_name='是否为默认')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2017, 12, 28, 11, 19, 24, 728395), verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esign_app.MyUser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '签名信息',
                'verbose_name_plural': '签名信息',
            },
        ),
        migrations.AddField(
            model_name='documents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esign_app.MyUser', verbose_name='用户'),
        ),
    ]
