# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 02:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='is_signed',
            field=models.CharField(default='0', max_length=10, verbose_name='是否签名'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 2, 26, 9, 39722), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 2, 26, 9, 38736), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 2, 26, 9, 40490), verbose_name='创建时间'),
        ),
    ]
