# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 05:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0003_auto_20171229_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 5, 13, 56, 191194), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 5, 13, 56, 189353), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 29, 5, 13, 56, 192693), verbose_name='创建时间'),
        ),
    ]
