# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 07:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0004_auto_20171229_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='documents',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 15, 5, 36, 733180), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 15, 5, 36, 732060), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 15, 5, 36, 734030), verbose_name='创建时间'),
        ),
    ]
