# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 08:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0005_auto_20180104_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='left_time',
            field=models.IntegerField(default=0, verbose_name='剩余时间'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 16, 10, 55, 576244), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 16, 10, 55, 574354), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 4, 16, 10, 55, 577692), verbose_name='创建时间'),
        ),
    ]
