# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 07:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0006_auto_20180104_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 8, 15, 58, 40, 322217), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 8, 15, 58, 40, 324647), verbose_name='创建时间'),
        ),
    ]
