# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 02:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0008_auto_20180110_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.IntegerField(default=0, verbose_name='持续时间')),
                ('ori_price', models.FloatField(default=0, verbose_name='原价')),
                ('now_price', models.FloatField(default=0, verbose_name='现价')),
            ],
            options={
                'verbose_name': 'vip信息',
                'verbose_name_plural': 'vip信息',
            },
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 17, 10, 39, 0, 767948), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 17, 10, 39, 0, 769857), verbose_name='创建时间'),
        ),
    ]
