# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0012_auto_20180119_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_party', models.CharField(max_length=20, null=True, verbose_name='甲方')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='联系地址')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='联系电话')),
                ('application_scene', models.CharField(max_length=100, null=True, verbose_name='应用场景')),
                ('date', models.CharField(max_length=20, null=True, verbose_name='日期')),
                ('trade_accounts', models.CharField(max_length=200, null=True, verbose_name='交易宝账号')),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 22, 17, 26, 34, 336458), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 22, 17, 26, 34, 338073), verbose_name='创建时间'),
        ),
    ]
