# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 05:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0013_auto_20180122_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_name', models.CharField(max_length=300, null=True, verbose_name='模版名称')),
                ('demo_url', models.CharField(max_length=300, null=True, verbose_name='模版地址')),
            ],
        ),
        migrations.RenameField(
            model_name='contract_info',
            old_name='date',
            new_name='date1',
        ),
        migrations.AddField(
            model_name='contract_info',
            name='date2',
            field=models.CharField(max_length=20, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 13, 58, 10, 585820), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 24, 13, 58, 10, 587457), verbose_name='创建时间'),
        ),
    ]
