# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 09:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0016_auto_20180125_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_info',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='esign_app.MyUser', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 25, 17, 30, 45, 808130), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 25, 17, 30, 45, 809795), verbose_name='创建时间'),
        ),
    ]
