# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 02:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0019_auto_20180129_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_party', models.CharField(max_length=20, null=True, verbose_name='甲方')),
                ('ID_card', models.CharField(max_length=18, null=True, verbose_name='身份证号')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='联系地址')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='联系电话')),
                ('copies', models.IntegerField(default=1, verbose_name='投资份数')),
                ('money_upper', models.CharField(max_length=100, null=True, verbose_name='投资金额大写(万元)')),
                ('money', models.FloatField(default=0, verbose_name='投资金额')),
                ('start_date', models.CharField(max_length=20, null=True, verbose_name='起投日期')),
                ('account_holder8', models.CharField(max_length=20, null=True, verbose_name='开户人')),
                ('account_bank8', models.CharField(max_length=20, null=True, verbose_name='开户行')),
                ('account8', models.CharField(max_length=20, null=True, verbose_name='账号')),
                ('account_holder10', models.CharField(max_length=20, null=True, verbose_name='开户人')),
                ('account_bank10', models.CharField(max_length=20, null=True, verbose_name='开户行')),
                ('account10', models.CharField(max_length=20, null=True, verbose_name='账号')),
                ('create_date', models.CharField(max_length=20, null=True, verbose_name='签订日期')),
            ],
        ),
        migrations.RenameModel(
            old_name='Contract_info',
            new_name='Trade_contract',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 10, 26, 5, 474545), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 10, 26, 5, 476226), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='financingcontract',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='esign_app.MyUser', verbose_name='用户'),
        ),
    ]
