# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 02:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0020_auto_20180131_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_demo',
            name='demo_type',
            field=models.CharField(default='trade_contract', max_length=300, verbose_name='模版地址'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 10, 45, 44, 987669), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 31, 10, 45, 44, 990129), verbose_name='创建时间'),
        ),
    ]
