# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 09:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0023_auto_20180201_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_demo',
            name='size',
            field=models.FloatField(default=3000000, verbose_name='容量'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 17, 36, 37, 819657), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 17, 36, 37, 822826), verbose_name='创建时间'),
        ),
    ]
