# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 10:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign_app', '0024_auto_20180205_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='vip_end_date',
            field=models.DateTimeField(null=True, verbose_name='vip过期时间'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 18, 5, 15, 740096), verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 18, 5, 15, 742367), verbose_name='创建时间'),
        ),
    ]
